[package]
name = "imcp-embedded"
version = "0.1.0"
edition = "2024"

[dependencies]
embassy-sync = { version = "0.7.2" }
embassy-executor = { version = "0.9.1" }
embassy-futures = { version = "0.1.1" }
embedded-io-async = "0.7.0"
embedded-hal = "1.0.0"
embassy-time = { version = "0.5.0" }
