[package]
name = "imcp-cli"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.51", features = ["derive"] }
clap-num = "1.2.0"
env_logger = "0.11.8"
hex = "0.4.3"
imcp = { path = "../../imcp" }
log = "0.4.28"
serialport = "4.8.1"
